blueprint:
  name: Fade on lights in the evening if motion is detected
  description: Fade on lights in the evening if motion is detected, but stops after a certain time
  domain: automation
  source_url: https://github.com/jhueppauff/HomeAssistantBlueprints/blob/main/motion_activated_nightlight.yml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light(s) to control
      selector:
        target:
          entity:
            domain: light
    sunset_offset:
      name: Offset to turn on lights
      description: Define offset to sunset
      default: -20
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes
    sunset_offset_off:
      name: Offset to stop the trigger
      description: Define when the trigger should be deactivated
      default: +40
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  - condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: !input sunset_offset
      - condition: sun
        before: sunset
        before_offset: !input sunset_offset_off

action:
  - service: light.turn_on
    target: !input light_target
    data:
      brightness: 255
      transition:  1800
