blueprint:
  name: Motion and Switch Activated Light
  description: Turn on a light with motion or switch, with reduced brightness after 8 PM. Turn off the light with the switch.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor to trigger the light
      selector:
        entity:
          domain: binary_sensor
    wall_switch:
      name: Wall Switch
      description: The wall switch to trigger the light
      selector:
        entity:
          domain: action
          integration: mqtt
    light_target:
      name: Light
      description: The light to be controlled
      selector:
        entity:
          domain: light
    after_time:
      name: Time for Reduced Brightness
      description: Time after which the light should turn on with reduced brightness
      default: '20:00:00'
      selector:
        time:
    reduced_brightness:
      name: Reduced Brightness Level
      description: Brightness level after the specified time
      default: 50
      selector:
        number:
          min: 1
          max: 255
    delay_off:
      name: Delay Before Turning Off
      description: Time to wait before turning off the light after motion stops
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'
  - platform: state
    entity_id: !input wall_switch
    to: 'on'

condition: []

action:
  - choose:
      - conditions:
          - condition: time
            after: !input after_time
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_target
            data:
              brightness: !input reduced_brightness
      - conditions: []
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_target
  - delay:
      minutes: !input delay_off
  - condition: state
    entity_id: !input motion_sensor
    state: 'off'
  - service: light.turn_off
    target:
      entity_id: !input light_target
  - alias: Turn off light on switch press
    trigger:
      - platform: state
        entity_id: !input wall_switch
        to: 'off'
    action:
      - service: light.turn_off
        target:
          entity_id: !input light_target

mode: restart
