blueprint:
  name: Multiple Input DayTime Dependend Light Control
  description: Blueprint to toggle a light based on a motion sensor or a switch. Dependend on the day time, the light will be dimmed. 
  domain: automation
  input:
    mqtt_device:
      name: MQTT Button
      description: The MQTT button to trigger the action.
      selector:
        device:
          integration: mqtt
    light_device:
      name: Light to Toggle
      description: The light to be toggled.
      selector:
        entity:
          domain: light

trigger:
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: left_press_release

action:
  - type: toggle
    device_id: !input light_device
    entity_id: !input light_device
    domain: light

mode: single
